# Live Financial Market Analytics & Forecasting

This notebook collects financial market data from an external API
and prepares it for further analysis and forecasting.

In [2]:
import requests
import pandas as pd
import os

from dotenv import load_dotenv

In [3]:
load_dotenv()

API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")

print("API Key Loaded:", API_KEY is not None)

API Key Loaded: True

In [4]:
SYMBOL = "AAPL"

print("Selected Stock:", SYMBOL)

Selected Stock: AAPL

In [4]:
BASE_URL = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": SYMBOL,
    "outputsize": "compact",
    "apikey": API_KEY
}

print("API request parameters created successfully.")

API request parameters created successfully.

In [5]:
response = requests.get(BASE_URL, params=params)

print("Status Code:", response.status_code)

Status Code: 200

In [6]:
data = response.json()

print(data.keys())

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [7]:
time_series = data["Time Series (Daily)"]

print(type(time_series))
print(list(time_series.items())[:2])

<class 'dict'>
[('2026-09-15', {'1. open': '330.1350', '2. high': '331.7800', '3. low': '328.3500', '4. close': '331.3400', '5. volume': '31748183'}), ('2026-09-14', {'1. open': '334.7900', '2. high': '335.5000', '3. low': '331.3400', '4. close': '333.0800', '5. volume': '39269147'})]

In [9]:
df = pd.DataFrame.from_dict(time_series, orient="index")

df.head()

             1. open   2. high    3. low  4. close 5. volume
2026-09-15  330.1350  331.7800  328.3500  331.3400  31748183
2026-09-14  334.7900  335.5000  331.3400  333.0800  39269147
2026-09-11  327.4500  336.2200  326.3000  332.2700  50716865
2026-09-10  316.6700  326.7400  316.5100  326.5700  70011913
2026-09-09  315.4850  319.1500  309.9000  315.3400  65639962

In [10]:
df.columns = [
    "Open",
    "High",
    "Low",
    "Close",
    "Volume"
]

df.head()

                Open      High       Low     Close    Volume
2026-09-15  330.1350  331.7800  328.3500  331.3400  31748183
2026-09-14  334.7900  335.5000  331.3400  333.0800  39269147
2026-09-11  327.4500  336.2200  326.3000  332.2700  50716865
2026-09-10  316.6700  326.7400  316.5100  326.5700  70011913
2026-09-09  315.4850  319.1500  309.9000  315.3400  65639962

In [11]:
df.index = pd.to_datetime(df.index)

df.index.name = "Date"

df.head()

                Open      High       Low     Close    Volume
Date
2026-09-15  330.1350  331.7800  328.3500  331.3400  31748183
2026-09-14  334.7900  335.5000  331.3400  333.0800  39269147
2026-09-11  327.4500  336.2200  326.3000  332.2700  50716865
2026-09-10  316.6700  326.7400  316.5100  326.5700  70011913
2026-09-09  315.4850  319.1500  309.9000  315.3400  65639962

In [12]:
numeric_columns = ["Open", "High", "Low", "Close", "Volume"]

df[numeric_columns] = df[numeric_columns].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 100 entries, 2026-09-15 to 2026-04-23
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    100 non-null    float64
 1   High    100 non-null    float64
 2   Low     100 non-null    float64
 3   Close   100 non-null    float64
 4   Volume  100 non-null    float64
dtypes: float64(5)
memory usage: 4.7 KB

In [13]:
df = df.sort_index()

df.head()

               Open    High     Low   Close      Volume
Date
2026-04-23  275.045  275.77  271.65  273.43  33399639.0
2026-04-24  272.755  273.06  269.65  271.06  38157110.0
2026-04-27  266.090  268.36  265.07  267.61  41466762.0
2026-04-28  272.335  273.23  268.66  270.71  40018940.0
2026-04-29  267.550  271.04  267.04  270.17  30047869.0

In [14]:
print("Dataset Shape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (100, 5)

Missing Values:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

Data Types:
Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [18]:
df.to_csv("data/market_data.csv", index=True)

print("Market data saved successfully.")

Market data saved successfully.